version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput & python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    volumes:
      - .:/evacode
    env_file:
      - .env
  update_database:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    command: python manage.py updatedata
    restart: always
    volumes:
      - .:/evacode
    env_file:
      - .env
#    depends_on:
#      - db
#    volumes:
#      - .:/evacode
#    env_file:
#      - .env
