version: "3.8"

services:
  db:
    container_name: evacode-db
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: evacode-api
    build:
      context: .
      network: host
      dockerfile: dockerfiles/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py createsuperuser --noinput & python manage.py create_currency & gunicorn evacode_backend.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static:/www/data/static
      - media:/www/data/media
  update_database:
    container_name: update_database
    network_mode: "host"
    build:
      context: .
      network: host
      dockerfile: dockerfiles/Dockerfile
    command: sh -c "python manage.py updatedata"
    restart: always
    depends_on:
      - server
    env_file:
      - .env2
    volumes:
      - static:/www/data/static
      - media:/www/data/media
  nginx:
    container_name: evacode-nginx
    build: ./dockerfiles/nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - server
    volumes:
      - static:/www/data/static
      - media:/www/data/media
      - ./dockerfiles/nginx/www.evacode.org.crt:/etc/ssl/private/www.evacode.org.crt
      - ./dockerfiles/nginx/www.evacode.org.key:/etc/ssl/private/www.evacode.org.key
  frontend:
    build: evacode.org
    depends_on:
      - nginx
volumes:
  pgdata:
    name: evacode-pgdata
  static:
    name: evacode-static
  media:
    name: evacode-media
