# Generated by Django 5.0.4 on 2026-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceyookassa',
            name='manager_name',
            field=models.CharField(default='a', max_length=64, verbose_name='Имя менеджера'),
            preserve_default=False,
        ),
    ]
