# Generated by Django 5.0.4 on 2026-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoiceyookassa_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Транзакции'),
        ),
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
