# Generated by Django 5.0.4 on 2026-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoiceyookassa_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceyookassa',
            name='customer_email',
            field=models.CharField(default='Email', max_length=64, verbose_name='Почта пользоавтеля/покупателя'),
        ),
        migrations.AddField(
            model_name='invoiceyookassa',
            name='customer_name',
            field=models.CharField(default='Имя', max_length=128, verbose_name='Имя пользователя/покупателя'),
        ),
        migrations.AddField(
            model_name='invoiceyookassa',
            name='customer_phone',
            field=models.CharField(default='Телефон', max_length=64, verbose_name='Номер телефона пользователя/покупателя'),
        ),
        migrations.AddField(
            model_name='invoiceyookassa',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
