# Generated by Django 5.0.4 on 2026-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoiceyookassa_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
