# Generated by Django 5.0.4 on 2026-02-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoiceyookassa_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
