# Generated by Django 5.0.4 on 2026-02-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoiceyookassa_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTossPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Транзакции')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(default='Имя', max_length=128, verbose_name='Имя пользователя/покупателя')),
                ('customer_phone', models.CharField(default='Телефон', max_length=64, verbose_name='Номер телефона пользователя/покупателя')),
                ('customer_email', models.CharField(default='customer_email@example.com', max_length=64, verbose_name='Почта пользоавтеля/покупателя')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_link', models.TextField(verbose_name='Ссылка на оплату')),
                ('manager_name', models.CharField(max_length=64, verbose_name='Имя менеджера')),
            ],
        ),
        migrations.AlterField(
            model_name='invoiceyookassa',
            name='customer_email',
            field=models.CharField(default='customer_email@example.com', max_length=64, verbose_name='Почта пользоавтеля/покупателя'),
        ),
    ]
