# Generated by Django 5.0.4 on 2026-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoicetosspayments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetosspayments',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Оплата корейской картой'), ('FOREIGN_EASY_PAY', 'Оплата иностранными картами')], db_index=True, default='CARD', max_length=16),
        ),
    ]
