# Generated by Django 5.0.4 on 2026-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_invoicetosspayments_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetosspayments',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Order ID'),
        ),
    ]
