# Generated by Django 5.0.4 on 2026-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_invoiceyookassa_manager_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceyookassa',
            name='manager_link',
        ),
        migrations.AddField(
            model_name='invoicetosspayments',
            name='manager_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на контакт менеджера'),
        ),
    ]
