# Generated by Django 5.0.4 on 2026-03-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_invoiceyookassa_manager_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetosspayments',
            name='payload',
            field=models.TextField(blank=True, null=True, verbose_name='Payload field'),
        ),
    ]
