# Generated by Django 5.0.3 on 2024-04-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_order', models.CharField(max_length=128)),
                ('deleted', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование группы')),
                ('updated', models.DateTimeField()),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.groupofgoods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=128)),
                ('official_price', models.PositiveIntegerField()),
                ('retail_price', models.PositiveIntegerField()),
                ('wholesale_price', models.PositiveIntegerField()),
                ('large_wholesale_price', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='market.groupofgoods')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField()),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.goodsmodel')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.groupofgoods')),
            ],
        ),
    ]
