# Generated by Django 5.0.4 on 2024-04-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_order', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(verbose_name='Крупный опт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование группы')),
                ('updated', models.DateTimeField(verbose_name='Обновлено')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.groupofgoods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Остатки')),
                ('official_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Официальная цена')),
                ('retail_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Розничная цена')),
                ('wholesale_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оптовая цена')),
                ('large_wholesale_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Крупный опт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='market.groupofgoods', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
                ('url', models.TextField(verbose_name='URL')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.goodsmodel', verbose_name='Товар')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.groupofgoods', verbose_name='Группа')),
            ],
        ),
    ]
