# Generated by Django 5.0.4 on 2024-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='bestseller',
            field=models.BooleanField(blank=True, null=True, verbose_name='Бест-селлер'),
        ),
    ]
