# Generated by Django 5.0.3 on 2024-04-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_goodsmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsmodel',
            old_name='retail_price',
            new_name='price',
        ),
    ]
