# Generated by Django 5.0.3 on 2024-04-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_retail_price_goodsmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='retail_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='market.groupofgoods', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='large_wholesale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Крупный опт'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='official_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Официальная цена'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='type',
            field=models.CharField(max_length=128, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='wholesale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='groupofgoods',
            name='deleted',
            field=models.BooleanField(verbose_name='Крупный опт'),
        ),
        migrations.AlterField(
            model_name='groupofgoods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='groupofgoods',
            name='updated',
            field=models.DateTimeField(verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.goodsmodel', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.groupofgoods', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='url',
            field=models.TextField(verbose_name='URL'),
        ),
    ]
