# Generated by Django 5.0.4 on 2024-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_goodsmodel_price_goodsmodel_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остатки'),
        ),
    ]
