# Generated by Django 5.0.4 on 2024-04-18 20:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=128, verbose_name='Telegram')),
                ('instagram', models.CharField(max_length=128, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=128, verbose_name='Facebook')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(verbose_name='Тип доставки')),
                ('delivery_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
