# Generated by Django 5.0.4 on 2024-06-21 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_delivery_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/reviews/avatars/', verbose_name='Аватар')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('review_photo', models.ImageField(upload_to='images/reviews/photos/', verbose_name='Фото')),
            ],
        ),
    ]
