# Generated by Django 5.0.4 on 2024-04-19 12:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus_contacts_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
