# Generated by Django 5.0.4 on 2024-06-24 16:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='tiktok',
            field=models.CharField(max_length=128, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст отзыва'),
        ),
    ]
