# Generated by Django 5.0.4 on 2024-06-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sectionwithvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
