# Generated by Django 5.0.4 on 2024-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название курса')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс валюты')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Курсы валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
